- name: Set Up RHEL environment
  hosts: all
  gather_facts: true
  become: false
  vars:
    GIT_PAT: "{{ lookup('env', 'GIT_PAT') }}"
  tasks:

    - name: Create a '.bin' directory in home directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.bin"
        state: directory
        mode: '0755'

    - name: Add '.bin' directory in PATH
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        regexp: '^export PATH=.*'
        line: 'export PATH={{ ansible_user_dir }}/bin:$PATH'
        insertafter: EOF
        state: present

    - name: Set Variable for Python Packages
      ansible.builtin.set_fact:
        python_packages:
          - "ansible"
          - "requests"
          - "pandas"

    - name: Create a Python Virtual environment
      ansible.builtin.pip:
        virtualenv: "{{ ansible_user_dir }}/.venv"
        virtualenv_python: "python3"
        state: present
      loop: "{{ python_packages }}"


    - name: Copy your Git Config to Home Directory
      ansible.builtin.copy:
        src: "~/.gitconfig"
        dest: "{{ ansible_user_dir }}/.gitconfig"
        owner: "{{ ansible_user_id }}"

    - name: Create an SSH Key
      community.crypto.openssh_keypair:
        path: "{{ ansible_user_dir }}/.ssh/id_rsa"
        group: "{{ ansible_user_id }}"
        owner: "{{ ansible_user_id }}"
        state: "present"
        type: "rsa"
        size: 4096
        mode: 0600

    - name: Create a SSH Config file
      ansible.builtin.template:
        src: "templates/ssh_config.js"
        dest: "{{ ansible_user_dir }}/.ssh/config"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: 0644

    - name: Add GitHub CLI repository
      ansible.builtin.yum_repository:
        name: github-cli
        description: GitHub CLI
        baseurl: https://cli.github.com/packages/rpm/
        enabled: yum_repository
        gpgcheck: yes
        gpgkey: https://cli.github.com/packages/rpm/gh-cli.repo
        become: true

    - name: Install Packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
        become: true
      loop:
        - "python3-pip"
        - "git"
        - "gh"

    - name: Authenticate to GitHub using GH CLI
      ansible.builtin.shell: echo "{{ GIT_PAT }}" | gh auth login --with-token

    - name: Add Public SSH Key to GitHub
      community.general.github_key:
        name: "ssh-key-rhel-vm-1"
        token: "{{GIT_PAT }}"
        pubkey: "{{ lookup('file', '{{ ansible_user_dir }}/.ssh/id_rsa.pub') }}"
        state: "present"

    - name: Set Variable with Aliases
      ansible.builtin.set_fact:
        aliases:
          - "alias activate='source {{ ansible_user_dir }}/venv/bin/activate'"
          - "alias pip=pip3"
          - "alias python=python3"

    - name: Create Aliases
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        line: "{{ item }}"
        state: present
      loop: "{{ aliases }}"

    - name: Reload bashrc to Apply Changes
      ansible.builtin.shell: source {{ ansible_user_dir }}/.bashrc
      args:
        executable: /bin/bash
